version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.0.442-node
        command: "/bin/bash"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "core/deps.edn" }}
            - v1-dependencies-
            - v1-npm-deps-{{ checksum "core/yarn.lock" }}
            - v1-npm-deps-

      - run: cd core && yarn

      - run: cd core && scripts/test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "core/deps.edn" }}

      - save_cache:
          paths:
            - ~/.yarn
          key: v1-npm-deps-{{ checksum "core/yarn.lock" }}

workflows:
  version: 2
  test:
    jobs:
      - build
