version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.0.442-node
        command: "/bin/bash"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies- # fallback if cache not found

      - run: clojure -Spath
      - run: clojure -A:dev:test -m cljs.main -re node -m uix.compiler-test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}

workflows:
  version: 2
  test:
    jobs:
      - build
